name: ECR-DOCKERIMAGE-PUSH

on:
  workflow_dispatch

jobs:
  ci_cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1.5.10
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Amazon ECR Login
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image variables
        id: vars
        run: |
          file: /pythonflask/Dockerfile
          IMAGE_TAG="latest"
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
          FULL_IMAGE="${{ steps.login-ecr.outputs.registry }}/${{secrets.ECR_REPOSITORY }}:$IMAGE_TAG"
          echo "FULL_IMAGE=$FULL_IMAGE" >> $GITHUB_ENV
      
      - name: Debug Print
        run: |
         echo "FULL_IMAGE = $FULL_IMAGE"
         echo "${IMAGE_TAG}"
  
      - name: Build Docker image
        run: |
         echo "file - $file1"
         docker build -t $FULL_IMAGE .$file
      - name: Show Docker image
        run: echo "image is - "${IMAGE_TAG}"
        
      - name: Push Docker image to Amazon ECR
        run: |
          docker push $FULL_IMAGE:latest 

      #- name: Build, tag, and push image to Amazon ECR
      #  id: build-image
      #  env:
      #   ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      #    IMAGE_TAG: ${{ github.sha }}
      #  run: |
      #   # Build a docker container and and push it to ECR
      #    docker build -t $ECR_REGISTRY/${{secrets.ECR_REPOSITORY }}:$IMAGE_TAG .pythonflask/Dockerfile
      #   docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
      #    echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
